/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/collection-detail`; params?: Router.UnknownInputParams; } | { pathname: `/collections`; params?: Router.UnknownInputParams; } | { pathname: `/conclusion`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/intro`; params?: Router.UnknownInputParams; } | { pathname: `/mood`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/path-complete`; params?: Router.UnknownInputParams; } | { pathname: `/path-day`; params?: Router.UnknownInputParams; } | { pathname: `/path-detail`; params?: Router.UnknownInputParams; } | { pathname: `/paths`; params?: Router.UnknownInputParams; } | { pathname: `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/questionnaire-response`; params?: Router.UnknownInputParams; } | { pathname: `/questionnaire`; params?: Router.UnknownInputParams; } | { pathname: `/recipe-card`; params?: Router.UnknownInputParams; } | { pathname: `/recipe-picker`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/thank-you`; params?: Router.UnknownInputParams; } | { pathname: `/trace`; params?: Router.UnknownInputParams; } | { pathname: `/verse`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/collection-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/collections`; params?: Router.UnknownOutputParams; } | { pathname: `/conclusion`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/intro`; params?: Router.UnknownOutputParams; } | { pathname: `/mood`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/path-complete`; params?: Router.UnknownOutputParams; } | { pathname: `/path-day`; params?: Router.UnknownOutputParams; } | { pathname: `/path-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/paths`; params?: Router.UnknownOutputParams; } | { pathname: `/paywall`; params?: Router.UnknownOutputParams; } | { pathname: `/questionnaire-response`; params?: Router.UnknownOutputParams; } | { pathname: `/questionnaire`; params?: Router.UnknownOutputParams; } | { pathname: `/recipe-card`; params?: Router.UnknownOutputParams; } | { pathname: `/recipe-picker`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/thank-you`; params?: Router.UnknownOutputParams; } | { pathname: `/trace`; params?: Router.UnknownOutputParams; } | { pathname: `/verse`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/collection-detail${`?${string}` | `#${string}` | ''}` | `/collections${`?${string}` | `#${string}` | ''}` | `/conclusion${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/intro${`?${string}` | `#${string}` | ''}` | `/mood${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/path-complete${`?${string}` | `#${string}` | ''}` | `/path-day${`?${string}` | `#${string}` | ''}` | `/path-detail${`?${string}` | `#${string}` | ''}` | `/paths${`?${string}` | `#${string}` | ''}` | `/paywall${`?${string}` | `#${string}` | ''}` | `/questionnaire-response${`?${string}` | `#${string}` | ''}` | `/questionnaire${`?${string}` | `#${string}` | ''}` | `/recipe-card${`?${string}` | `#${string}` | ''}` | `/recipe-picker${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/thank-you${`?${string}` | `#${string}` | ''}` | `/trace${`?${string}` | `#${string}` | ''}` | `/verse${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/collection-detail`; params?: Router.UnknownInputParams; } | { pathname: `/collections`; params?: Router.UnknownInputParams; } | { pathname: `/conclusion`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/intro`; params?: Router.UnknownInputParams; } | { pathname: `/mood`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/path-complete`; params?: Router.UnknownInputParams; } | { pathname: `/path-day`; params?: Router.UnknownInputParams; } | { pathname: `/path-detail`; params?: Router.UnknownInputParams; } | { pathname: `/paths`; params?: Router.UnknownInputParams; } | { pathname: `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/questionnaire-response`; params?: Router.UnknownInputParams; } | { pathname: `/questionnaire`; params?: Router.UnknownInputParams; } | { pathname: `/recipe-card`; params?: Router.UnknownInputParams; } | { pathname: `/recipe-picker`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/thank-you`; params?: Router.UnknownInputParams; } | { pathname: `/trace`; params?: Router.UnknownInputParams; } | { pathname: `/verse`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
